#ifndef _ENUMS_H
#define _ENUMS_H

typedef enum {
	KEYWORD_DEF,
	KEYWORD_ELSE,
	KEYWORD_IF,
	KEYWORD_NONE,
	KEYWORD_PASS,
	KEYWORD_RETURN,
	KEYWORD_WHILE,
	KEYWORD_AND,
	KEYWORD_OR,
	KEYWORD_IS,
	KEYWORD_NOT,
	KEYWORD_TRUE,
	KEYWORD_FALSE,
	KEYWORD_INTEGER,
	KEYWORD_DOUBLE,
	KEYWORD_STRING,
	KEYWORD_CHAR,

	TOKEN_EOL,		// end of line
	TOKEN_EOF,		// end of file
	TOKEN_ASSIGN,		// =
	TOKEN_GREATER_THAN,	// >
	TOKEN_LESSER_THAN,	// <
	TOKEN_PLUS,		// +
	TOKEN_MINUS,		// -
	TOKEN_DIVISION,		// /
	TOKEN_MULTIPLICATION,	// *
	TOKEN_LEFT_BRACKET,		// (
	TOKEN_RIGHT_BRACKET,	// )
	TOKEN_LEFT_SQUARE_BRACKET, // [
	TOKEN_RIGHT_SQUARE_BRACKET, // ]
	TOKEN_SINGLE_QUOTE,			// '
	TOKEN_DOUBLE_QUOTE,			// "
	TOKEN_INDENT,
	TOKEN_DEDENT,
	TOKEN_HASH,					// #
	TOKEN_PERCENT,				// %
	TOKEN_COLON,				// :
	TOKEN_COMMA,				// ,
} Token_type;

#endif
